### ISSUE TITLE
option (or parameter?) to restrict width

### ISSUE THREAD

**Issue by igalic** [kneufeld/consolemd#10]
`--soft-wrap` is very useful when the source-material is formatted to fit into a readable width.
`--no-soft-wrap` is very useful when your console is a readable amount of COLUMNS…

when neither, it would be nice to have a way to ask `consolemd` for hard-breaks at a specific width.

for instance, on Linux i set `MANWIDTH=72`, so that on my full-screen terminal (`COLUMNS=174`) i can *actually* read man pages.

`cat foo.md | env COLUMNS=72 consolemd` does not seem to work, so perhaps we need to actually need to implement something here?

**Comment by igalic** [comment]
Apparently, what i'm looking for is: `cat foo.md | fold -sw 72 | consolemd` 😅

**Comment by kneufeld** [comment]
That's a good idea, I've pushed `v0.5.0` which has a `--width / -w` cmdline arg and defaults to `CONSOLEMD_WIDTH` or `MANWIDTH`. I've also added your handle to `CONTRIBUTORS.md`

**Comment by igalic** [comment]
💜\o/💜
