### ISSUE TITLE
error with python 3.6

### ISSUE THREAD

**Issue by tofulm** [kneufeld/consolemd#3]
in styler.py : 
change : 
L64 `return list(filter(lambda val: val.startswith('#'), values))[0]` 
L70 `bg = list(filter(lambda val: val.startswith('bg:'), values))[0]`

and in renderer.py
change : 
L63 : `stream.write(out.decode('utf-8'))`

It's ok with this change.

**Comment by kneufeld** [comment]
I'll try to get a new version on PyPI tomorrow, if I haven't by Sunday then please call me out on it.

Thanks fellow markdown enthusiasts!
