### ISSUE TITLE
TypeError: 'filter' object is not subscriptable

### ISSUE THREAD

**Issue by fboender** [kneufeld/consolemd#5]
Hey Kurt!

I'm running into a `TypeError: 'filter' object is not subscriptable` error right after installing and running consolemd on a simple Markdown file.

I've installed consolemd in a virtualenv, like so:

    fboender @ jib ~/Temp $ virtualenv -p python3 foobar
    Already using interpreter /usr/bin/python3
    Using base prefix '/usr'
    New python executable in /home/fboender/Temp/foobar/bin/python3
    Also creating executable in /home/fboender/Temp/foobar/bin/python
    Installing setuptools, pkg_resources, pip, wheel...done.

    fboender @ jib ~/Temp $ cd foobar/

    fboender @ jib ~/Temp/foobar $ . bin/activate

    (foobar) fboender @ jib ~/Temp/foobar $ pip3 install consolemd
    Collecting consolemd
      Using cached https://files.pythonhosted.org/packages/27/bb/2a8dea501fa3fc0df1e09077fe139cd17eba0e592e5d9c7a2cd9193b8326/consolemd-0.3.2-py2.py3-none-any.whl
    Collecting commonmark<1.0 (from consolemd)
      Using cached https://files.pythonhosted.org/packages/8a/5c/625ac1a93da3a672f52d947023770331b958a1100cd9889b727cde5f7ba5/CommonMark-0.7.5-py2.py3-none-any.whl
    Collecting pygments<3.0 (from consolemd)
      Downloading https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl (841kB)
        100% |████████████████████████████████| 849kB 857kB/s 
    Collecting setproctitle<1.2 (from consolemd)
    Collecting click<7.0 (from consolemd)
      Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
    Collecting future (from commonmark<1.0->consolemd)
    Installing collected packages: future, commonmark, pygments, setproctitle, click, consolemd
    Successfully installed click-6.7 commonmark-0.7.5 consolemd-0.3.2 future-0.16.0 pygments-2.2.0 setproctitle-1.1.10

But when I try to run consolemd, I get a "`TypeError: 'filter' object is not subscriptable`" error:

    (foobar) fboender @ jib ~/Temp/foobar $ consolemd /home/fboender/Projects/fboender/garner/README.md 
    Traceback (most recent call last):
      File "/home/fboender/Temp/foobar/bin/consolemd", line 11, in <module>
        sys.exit(cli())
      File "/home/fboender/Temp/foobar/lib/python3.5/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/fboender/Temp/foobar/lib/python3.5/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/fboender/Temp/foobar/lib/python3.5/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/fboender/Temp/foobar/lib/python3.5/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/fboender/Temp/foobar/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/home/fboender/Temp/foobar/lib/python3.5/site-packages/consolemd/cli.py", line 100, in cli
        renderer.render( md, **kw )
      File "/home/fboender/Temp/foobar/lib/python3.5/site-packages/consolemd/renderer.py", line 51, in render
        self.styler = Styler( stream, self.style_name)
      File "/home/fboender/Temp/foobar/lib/python3.5/site-packages/consolemd/styler.py", line 102, in __init__
        self.style = Style(style_name)
      File "/home/fboender/Temp/foobar/lib/python3.5/site-packages/consolemd/styler.py", line 38, in __init__
        'heading':      (f(token.Generic.Heading , solarized['heading'])     , None) ,
      File "/home/fboender/Temp/foobar/lib/python3.5/site-packages/consolemd/styler.py", line 76, in eseq_from_pygments
        fg        = fg(values),
      File "/home/fboender/Temp/foobar/lib/python3.5/site-packages/consolemd/styler.py", line 64, in fg
        return filter(lambda val: val.startswith('#'), values)[0]
    TypeError: 'filter' object is not subscriptable

I've reduced the contents of the README.md I was trying to view to the following, which still reproduces the problem:

    Garner is a service integration and automation framework.

I'm running on the following software:

    (foobar) fboender @ jib ~ $ cat /etc/lsb-release 
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

    (foobar) fboender @ jib ~ $ python --version
    Python 3.5.2

The README says Python v3 is supported?

It appears the `filter()` call returns a iterable rather than something that can indexed. I've modified the source for `consolemd/styler.py` to print the value of `values` and the result of applying the `filter()` call:

        def fg(values):
            try:
                print('values:', values)
                print('filter:', filter(lambda val: val.startswith('#'), values))
                return filter(lambda val: val.startswith('#'), values)[0]
            except IndexError:
                return ''

Output:

    (foobar) fboender @ jib ~ $ consolemd /home/fboender/Projects/fboender/garner/README.md 
    values: ['bold', '#ffffff']
    filter: <filter object at 0x7f526e789a58>

This seems to be in accordance with how `filter()` works after Python v2 (I think?):

    >>> l = [3, 9, 81, 6561]
    >>> r = filter(lambda x: x > 9, l)

    >>> r[0]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: 'filter' object is not subscriptable
    'filter' object is not subscriptable

    >>> for x in r:
      2     print(x)
    81
    6561

One (ugly?) solution for this problem would be to use `next()`:

    >>> r = filter(lambda x: x > 9, l)
    >>> next(r)
    81

Regards,

Ferry

**Comment by kneufeld** [comment]
Thanks so much for reporting this to me! I was able to duplicate your results.

So I have no idea what's going on but I _think_ I only uploaded `v0.4.0` to the testing `pypi` repo and not the real one. You were downloading an older version.

Well I've made a new version and uploaded it for reals. When I ran `pip install -U consolemd` it didn't actually get the new version (maybe still in cache window) so I then tried `pip install --upgrade --no-cache-dir consolemd` and that was able to upgrade just fine.

So I'll be adding `--version` to the command line...

**Comment by kneufeld** [comment]
To answer your implied question, in `v.0.4.0` I solved the problem by wrapping `filter` with `list`.

```python
return list(filter(lambda val: val.startswith('#'), values))[0]
```

but just now in `v0.4.1` I did it the proper way with a list comprehension

```python
return [val for val in values if val.startswith('#')][0]
```

**Comment by kneufeld** [comment]
```
$ consolemd --version
0.4.2
```
