### ISSUE TITLE
Prints what looks like a version number

### ISSUE THREAD

**Issue by vext01** [kneufeld/consolemd#6]
Hi,

I tried to use consolemd on OpenBSD with Python-3.6. I installed using pip:

```
$ cat a.md       
 * hi

this is 
a
test

\```
1
2
3
\```

 * 1
   2lkjklkjkfs
 * 2
 * 3445
   - j
```

(The backslashes are not in the file, that's to supress GH from marking it up).

```
$ which consolemd
/home/edd/.local/bin/consolemd
$ consolemd a.md
0.4.2
```

That doesn't seem right...

**Comment by kneufeld** [comment]
Well that's embarrassing... fixed. `v0.4.3` pushed to pypi.

Thanks for reporting that, you're now immortalized in the `CONTRIBUTORS.md`.
